In [1]:
import dispersion
import pandas as pd
import numpy as np
df = pd.read_csv('compact_planet_data.csv', index_col=0)

/home/miniconda3/envs/kaichen/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/miniconda3/envs/kaichen/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  warn(f"Failed to load image Python extension: {e}")


In [2]:
plist = [] # master plist, where each entry will be [P1,P2,..., PN] for each sim
for system in df['Host Name'].unique():
    periods = df[df['Host Name']==system]['Orbital Period'].values
    periods.sort()
    plist.append(periods)
plist
# populate trios with get_trios from rori code, drop the ones where the inner is not less than 1.5


[array([ 5.516,  6.584, 18.57 ]),
 array([ 17.133,  24.329, 106.3  ]),
 array([28.14 , 39.026, 62.24 ]),
 array([14.175685, 19.590025, 29.54115 ]),
 array([ 28.579743,  38.353037, 101.12    ]),
 array([ 5.75999,  7.28243, 10.86499, 25.1967 ]),
 array([12.1621839, 17.667087 , 29.79749  ]),
 array([ 5.24 ,  7.775, 10.115]),
 array([4.528598, 6.131243, 9.327527]),
 array([ 7.138048, 10.45582 , 14.76289 ]),
 array([ 4.44117,  6.42904, 14.09189]),
 array([ 6.679582,  9.715043, 13.62749 ]),
 array([ 5.577212,  7.760178, 15.189034]),
 array([0.2197 , 0.32528, 0.81161]),
 array([  7.008151,   8.719375,  14.44912 ,  91.93913 , 124.9144  ,
        210.60697 ]),
 array([ 5.28696,  7.07142, 10.3117 , 16.1457 ]),
 array([ 10.3039,  13.0241,  22.6845,  31.9996,  46.6888, 118.3807]),
 array([3.26663995, 4.27225018, 5.45298175]),
 array([10.3134, 13.7815, 23.0923]),
 array([2.89223021, 3.95116882, 5.10115756, 5.99273738]),
 array([ 6.195469,  8.348125, 13.767102]),
 array([ 7.466623, 11.131786, 16.259

In [7]:
len(df['Host Name'].unique())

49

In [3]:
trios = dispersion.get_trios(Plist = plist)
len(trios)

58

In [5]:
dispersion.dispersion(trios=trios)

(0.3024495566800291, 0.01800678803123943)